
services:
  mariadb:
    build:
      context: .
      dockerfile: srcs/requirements/mariadb/Dockerfile
    container_name: mdb_container
    ports:
      - "3306:3306"
    volumes:
      - mdb_data:/var/lib/mysql
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-MDB_NAME666}
      DATABASE_USER_NAME: ${DATABASE_USER_NAME:-MDB_USER666}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD:-MDB_PASSWD666}
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: srcs/requirements/nginx/Dockerfile
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mdb_data:
    driver: local

networks:
  inception:
    driver: bridge
